"""Initial migration with all models

Revision ID: bb38887b5a46
Revises: 
Create Date: 2026-02-26 14:52:26.917554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb38887b5a46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_clusters',
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('WATER_SUPPLY', 'ELECTRICITY', 'ROADS_INFRASTRUCTURE', 'HEALTHCARE', 'PUBLIC_SAFETY', 'SANITATION', name='category'), nullable=False),
    sa.Column('representative_description', sa.Text(), nullable=False),
    sa.Column('location_latitude', sa.Float(), nullable=True),
    sa.Column('location_longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_index(op.f('ix_duplicate_clusters_category'), 'duplicate_clusters', ['category'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('nearby_sensitive_locations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('officers',
    sa.Column('officer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.Enum('WATER_DEPT', 'ELECTRICITY_DEPT', 'ROADS_DEPT', 'HEALTH_DEPT', 'SAFETY_DEPT', 'SANITATION_DEPT', name='department'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('location_latitude', sa.Float(), nullable=True),
    sa.Column('location_longitude', sa.Float(), nullable=True),
    sa.Column('location_address', sa.String(length=500), nullable=True),
    sa.Column('assigned_cases', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('officer_id')
    )
    op.create_index(op.f('ix_officers_department'), 'officers', ['department'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('complaints',
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_officer_id', sa.String(length=36), nullable=True),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.Enum('WATER_SUPPLY', 'ELECTRICITY', 'ROADS_INFRASTRUCTURE', 'HEALTHCARE', 'PUBLIC_SAFETY', 'SANITATION', name='category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('severity_terms', sa.Text(), nullable=True),
    sa.Column('media_urls', sa.Text(), nullable=True),
    sa.Column('priority_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['officers.officer_id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['duplicate_clusters.cluster_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_priority_level'), 'complaints', ['priority_level'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_user_id'), 'complaints', ['user_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_feedbacks_complaint_id'), 'feedbacks', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_complaint_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_complaints_user_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority_level'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_officers_department'), table_name='officers')
    op.drop_table('officers')
    op.drop_table('locations')
    op.drop_index(op.f('ix_duplicate_clusters_category'), table_name='duplicate_clusters')
    op.drop_table('duplicate_clusters')
    # ### end Alembic commands ###
